name: uasmobile_kelompok4
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.1
  path_provider: ^2.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  flutter_local_notifications: ^17.2.4
  intl: ^0.20.2
  fl_chart: ^1.1.1
  pdf: ^3.11.0
  printing: ^5.13.4

  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  firebase_messaging: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true